apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hello-world
spec:
  replicas: 1
  # strategy:
  #   type: Recreate
  selector:
    matchLabels:
      app: node-hello-world
  template:
    metadata:
      labels:
        app: node-hello-world
    spec:
      containers:
      - image: node-hello-world
        name: node-hello-world
        ports:
          - containerPort: 3000
        imagePullPolicy: "Never"
---

apiVersion: v1
kind: Service
metadata:
  name: node-hello-world
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: node-hello-world
  type: LoadBalancer
